{% set version = "16.1.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-laplacesdemon
  version: {{ version|replace("-", "_") }}

source:
  fn: LaplacesDemon_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/LaplacesDemon_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/LaplacesDemon/LaplacesDemon_{{ version }}.tar.gz
  sha256: 64cc565589d242dcd59cf720df184f08e3ab3d8920dc947bdfd7f1ec52e54714

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('LaplacesDemon')"           # [not win]
    - "\"%R%\" -e \"library('LaplacesDemon')\""  # [win]

about:
  home: https://github.com/LaplacesDemonR/LaplacesDemon
  license: MIT
  license_file: LICENSE
  summary: Provides a complete environment for Bayesian inference using a variety of different samplers (see ?LaplacesDemon for an overview). The README describes the history of the package development process.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
