travis:
  secure:
    BINSTAR_TOKEN: mZZlTPmosO26y4fcrxEdHZw5Fy2KuYps9YDdHofoGEAJ7+lqa2Q3oDx9PBe3hY1JVnNVTh7YMjwDdwFqsvFMb4g3f2eO3f7DUemqv1KyKJHflJBK2468a3VjXCr89mZwXv17BrUbkv2VV4eX5ooiFfPlXfpqt9W+br1lUodDVmgygZkaW0PJTV1/7veQZPcM179PAteRAQT6SyfHXMGLEaK3NzSX6sKWseLr/czRcjPkLgUT+n4FIBKJ5hgNyXI9nFopqJSNwT+1owcvPtBgTQYTtG1z+VLxiqLcvTPK4qC8gOZI4ODKLgE2ANFn4FYxOU1lJkfyjo0C/faTTUfYlIDdy9twIABAUf4tERjW3FZJfYehgBQb4JfU6cEz0fRFXc/QwuSCEjsMgt9jE/IcLR4IG6Djh/b6ynto2LaJKyCT1/oib3AQEeyB2aq6c941oOQbt/CJCa8ijEhArNR1lGWmBdIb3jflNt/9wDmJ+d5yJ1/4iWleTpvgaDtJO1gDnJlkCBMHGsY+RD3sFOik20wveibUjoJFkiuov13Oxm0hsuGBBAvbsHI7jXKt25+rWCEK/n8a4oW8HEG7cbJko6ciXilsvzfy9JmIP7VDs4T8x2Yc5O1wCWfaC+1qOtWE3IIiCGDsW2ZrzXS5+awnNX9XYnzK5xv4n0DvnjzDDOo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
